### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by cphillips83** [madskristensen/MarkdownEditor#94]
Any chance we can get the preview window to respect the dark theme in VS2015?

**Comment by fjcalzado** [comment]
Same petition here

**Comment by ericwj** [comment]
Workaround is to create `md-styles.css` and pasting:
```CSS
body {
    background-color: black;
    color: white
}
```
At the very minimum.
